daemon:
  port: 8000
  host: localhost
logging:
  level: info
reports:
  format: pdf
  renderer: xhtml2pdf
  cacheDir: ~/.pebblo
classifier:
  anonymizeSnippets: False
storage:
  type: db
  db: sqlite
  location: ~/.pebblo
  name: pebblo
