daemon:
  port: 8000
  host: localhost
logging:
  level: info
reports:
  format: pdf
  renderer: xhtml2pdf
  cacheDir: ~/.pebblo
  anonymizeSnippets: False
classifier:
  mode: all
storage:
  type: file
