---
# Source: k8s/templates/config.yaml
# host: bind host for Pebblo Server
apiVersion: v1
kind: ConfigMap
metadata:
  name: pebblo-server-config
data:
  config.yaml: |
    daemon:
      port: 8000
      host: 0.0.0.0
    logging:
      level: info
    reports:
      format: pdf
      renderer: xhtml2pdf
      cacheDir: /opt/.pebblo
    classifier:
      anonymizeSnippets: False
