---
# Source: k8s/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebblo-server
  labels:
    app: pebblo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pebblo-server
  template:
    metadata:
      labels:
        app: pebblo-server
    spec:
      containers:
      - name: pebblo-server
        image: daxaai/pebblo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        resources:
          requests:
            cpu: "1000m"
            memory: "1000Mi"
        volumeMounts:
        - name: pebblo-config
          mountPath: "/opt/pebblo/config"
        - name: pebblo-server
          mountPath: /opt
      volumes:
      - name: pebblo-config
        configMap:
          name: pebblo-server-config
          items:
            - key: config.yaml
              path: config.yaml
      - name: pebblo-server
        persistentVolumeClaim:
          claimName: pebblo-server
