topic_entity_mapping = {
    "normal-text": "Normal Text",
    "medical-advice": "Medical Advice",
    "harmful-advice": "Harmful Advice",
    "board-meeting": "Board Meeting",
    "consulting-agreement": "Consulting Agreement",
    "customer-list": "Customer List",
    "distribution/partner-agreement": "Distribution/Partner Agreement",
    "enterprise-agreement": "Enterprise Agreement",
    "executive-severance-agreement": "Executive Severance Agreement",
    "financial-report": "Financial Report",
    "loan-and-security-agreement ": "Loan And Security Agreement",
    "merger-agreement": "Merger Agreement",
    "nda": "NDA",
    "patent-application-fillings": "Patent Application Fillings",
    "price-list": "Price List",
    "settlement-agreement": "Settlement Agreement",
    "sexual-content": "Sexual Content",
    "sexual-incident-report": "Sexual Incident Report",
    "employee-agreement": "Employee Agreement",
    "internal-product-roadmap-agreement": "Internal Product Roadmap Agreement",
    "us-ssn": "US SSN",
    "us-passport-number": "US Passport number",
    "us-drivers-license": "US Drivers License",
    "credit-card-number": "Credit card number",
    "us-bank-account-number": "US Bank Account Number",
    "iban-code": "IBAN code",
    "us-itin": "US ITIN",
    "github-token": "Github Token",
    "slack-token": "Slack Token",
    "aws-access-key": "AWS Access Key",
    "aws-secret-key": "AWS Secret Key",
    "azure-key-id": "Azure Key ID",
    "azure-client-secret": "Azure Client Secret",
    "google-api-key": "Google API Key",
}
