topic_entity_mapping = {
    "normal-text": "Normal Text",
    "medical-advice": "Medical Advice",
    "harmful-advice": "Harmful Advice",
    "board-meeting": "Board Meeting",
    "consulting-agreement": "Consulting Agreement",
    "customer-list": "Customer List",
    "distribution/partner-agreement": "Distribution/Partner Agreement",
    "enterprise-agreement": "Enterprise Agreement",
    "executive-severance-agreement": "Executive Severance Agreement",
    "financial-report": "Financial Report",
    "loan-and-security-agreement ": "Loan And Security Agreement",
    "merger-agreement": "Merger Agreement",
    "nda": "NDA",
    "patent-application-fillings": "Patent Application Fillings",
    "price-list": "Price List",
    "settlement-agreement": "Settlement Agreement",
    "sexual-content": "Sexual Content",
    "sexual-incident-report": "Sexual Incident Report",
    "employee-agreement": "Employee Agreement",
    "internal-product-roadmap-agreement": "Internal Product Roadmap Agreement",
    "us-ssn": "US SSN",
    "us-passport-number": "US Passport number",
    "us-drivers-license": "US Drivers License",
    "email-address": "Email Address",
    "person-name": "Person",
    "organization": "Organization",
    "street-address": "Street Address",
    "phone-number": "Phone Number",
    "date-of-birth": "Date Of Birth",
    "ip-address": "Ip Address",
    "credit-card-number": "Credit card number",
    "us-bank-account-number": "US Bank Account Number",
    "iban-code": "IBAN code",
    "us-itin": "US ITIN",
    "bank-routing-number": "Bank Routing Number",
    "swift-code": "Swift Code",
    "bban-code": "Bban Code",
    "github-token": "Github Token",
    "github-finegrained-token": "Github Finegrained Token",
    "private-key": "Private Key",
    "dsa-private-key": "DSA Private Key",
    "encrypted-private-key": "Encrypted Private Key",
    "ec-private-key": "Elliptic Curve Private Key",
    "openssh-private-key": "OpenSSH Private Key",
    "rsa-private-key": "RSA Private Key",
    "google-private-key": "Google Account Private Key",
    "slack-token": "Slack Token",
    "aws-access-key": "AWS Access Key",
    "aws-secret-key": "AWS Secret Key",
    "azure-key-id": "Azure Key ID",
    "azure-client-secret": "Azure Client Secret",
    "google-api-key": "Google API Key",
    "api-key": "Api Key",
    "harmful": "Harmful",
    "medical": "Medical",
    "financial": "Financial",
    "corporate-documents": "Corporate Documents",
    "GOVERNANCE": "Governance",
    "FINANCE": "Finance",
    "HR": "Hr",
    "HEALTH": "Health",
    "LEGAL": "Legal",
    "CUSTOMER": "Customer",
    "IP": "IP",
    "PRODUCT": "Product",
    "MARKETING": "Marketing",
    "SALES": "Sales",
    "SECURITY": "Security",
    "STRATEGY": "Strategy",
}
