topic_display_names = {
    "NORMAL_TEXT": "Normal Advice",
    "MEDICAL_ADVICE": "Medical Advice",
    "HARMFUL_ADVICE": "Harmful Advice",
    "Board meeting": "Board Meeting",
    "Consulting Agreement": "Consulting Agreement",
    "Customer List": "Customer List",
    "Distribution/Partner Agreement": "Distribution/Partner Agreement",
    "Enterprise License Agreement": "Enterprise License Agreement",
    "Executive Severance Agreement": "Executive Severance Agreement",
    "Financial Report": "Financial Report",
    "Internal Use Only": "Internal Use Only",
    "Loan and security Agreement": "Loan And Security Agreement",
    "Merger Agreement": "Merger Agreement",
    "NDA": "NDA",
    "Patent Application Fillings": "Patent Application Fillings",
    "Price list": "Price List",
    "Secret Sauce": "Secret Sauce",
    "Security Breach": "Security Breach",
    "Settlement Agreement": "Settlement Agreement",
    "Sexual Harrassment": "Sexual Harassment",
    "employee agreement": "Employee Agreement",
    "enterprise agreement": "Enterprise Agreement"
}
