name: CIDocsTest

on:
  pull_request:
    paths:
      - "docs/**/*"
jobs:
  PebbloDocsCITest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd docs/gh_pages
          npm install 
          npm run build
