# If you change this name also do it in linting.yml
name: Linting

on:
  pull_request:
    paths-ignore:
      - "docs/**/*.md"
      - "docs/**/*.png"
      - "docs/**/*.jpg"
      - "docs/**/*.yml"
      - "samples/**/*.md"
      - "**/pyproject.toml"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Skip mypy
        run: echo "Skipped mypy"

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Skip pylint
        run: echo "Skipped pylint"
