# If you change this name also do it in tests.yml
name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "pebblo/**/*.py"
      - "pebblo/**/*.txt"
jobs:
  catch-all:
    name: Catch-all check
    runs-on: ubuntu-latest
    steps:
      - name: Skip tests
        run: echo "Skipped!"
